# Lab 2
Bryan Christ

## Question 1 
https://github.com/bryanchrist/lab2

## Question 2

In [3]:
import pandas as pd
import numpy as np 
import requests 
from bs4 import BeautifulSoup
import collections
collections.Callable = collections.abc.Callable
import os

In [11]:
data_clean = pd.read_csv("data/data_clean.csv")
data_clean.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [12]:
data1 = pd.read_csv("data/data1.csv", header=2)
data1.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [15]:
data2 = pd.read_csv("data/data2.txt", header= 2, comment= "/")
data2.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [20]:
data3 = pd.read_csv("data/data3.txt", header=2, sep="\t")
data3.head(10)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,1.361,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,1.330,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,1.268,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,1.355,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,1.340,1.573,0.910,0.647,0.361,0.302

In [27]:
col_names = ['Country', 'Happiness Score', 'Whisker-high',
            'Whisker-low', 'Dystopia (1.92) + residual', 
            'Explained by: GDP per capita', 'Explained by: Social support', 
            'Explained by: Healthy life expectancy', 'Explained by: Freedom to make life choices',
            'Explained by: Generosity', 'Explained by: Perceptions of corruption']
data4 = pd.read_csv("data/data4.txt", sep="$", header=None, names=col_names)
data4.head(10)

,Country,Happiness Score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,1.361,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,1.330,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,1.268,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,1.355,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,1.340,1.573,0.910,0.647,0.361,0.302

In [39]:
data5 = pd.read_csv("data/data5.csv", skipfooter=2)
data5.tail()

/tmp/ipykernel_14/3607813398.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  data5 = pd.read_csv("data/data5.csv", skipfooter=2)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

In [69]:
data6 = pd.read_csv("data/data6.dat", na_values = 999)
data6.tail(6)
#Looks like missing data is the problem? Yemen needs name replace
#Ask Kropko

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
150,Rwanda,NaN,3.500,3.317,0.500,0.332,0.896,NaN,0.636,0.200,0.444
151,NaN,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,NaN,0.064
152,Tanzania,NaN,NaN,3.193,0.628,NaN,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,NaN,3.123,1.691,0.337,NaN,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,NaN,0.038
155,Burundi,2.905,3.074,NaN,1.752,0.091,NaN,0.145,0.065,0.149,0.076

In [47]:
data7 = pd.read_excel("data/data7.xlsx", sheet_name="Data")
data7.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [61]:
data8 = pd.read_stata("data/data8.dta")
data8.columns = col_names
data8.head() 
#Is this all for this one?

,Country,Happiness Score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [62]:
data9 = pd.read_spss("data/data9.sav")
data9.columns = col_names
data9.head()
#Is this all for this one? Column names are slightly different

,Country,Happiness Score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [63]:
data10 = pd.read_sas("data/data10.xpt")
data10.columns = col_names
data10.head()
#This one good too?

,Country,Happiness Score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,b'Finland',7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,b'Norway',7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,b'Denmark',7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,b'Iceland',7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,b'Switzerland',7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

# Question 3